language: php
dist: xenial
sudo: true

git:
  depth: 5

notifications:
  email:
    - lisa@codementality.com
  on_success: change
  on_failure: always

php:
  - 7.3

# Build only when changes are pushed on or merged into develop branch
branches:
  only:
  - develop

before_install:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini
  - composer --verbose self-update --$COMPOSER_CHANNEL
  - composer --version

script:
  - ./build-project.sh
